### PR TITLE
Timezone management

### PR DESCRIPTION
**Pull request by ArKniiD**
Added timezone management for default scheduled time and launching time calculation.

### CODE REVIEW

**Comment by sgrillon14** [comment]
I work in France, this PR is essential for my development, thanks. @ArKniiD, good job.

Admin screenshot:

pr7

**Comment by ArKniiD** [comment]
I added a fix to a bug in index.jelly in order to not have double slashes in _checkUrl_ when checking scheduled date. This is useful if somebody use a reverse proxy with specific security rules (like banning '//' in URLs).

**Comment by pingunaut** [comment]
Thanks a lot, I'll try to integrate this PR asap. Nice feature!

**Comment by pingunaut** [comment]
Hi @ArKniiD and @sgrillon14,
release 0.4.0-beta will be available within the next hours from the experimental update center.
Do you have the chance to do a test and provide some feedback?
Best regards and thanks a lot!

**Comment by ArKniiD** [comment]
Hi @pingunaut,

I will do some tests locally ASAP. I'll let you know when it's done.
Sorry for the delay

Best regards

**Comment by pingunaut** [comment]
Hi @ArKniiD,
no problem. I got some positive feedback, so I did already release 0.4.0, so you do not even have to change to experimental update center to test :)

Best regards

**Pull request merged**
