### PR TITLE
Require Jenkins 2.346.3 or newer

### PR DESCRIPTION
**Pull request by anurag-sachan**
## Require Jenkins 2.346.3 or newer

- [X] I have read the [CONTRIBUTING](https://github.com/jenkinsci/schedule-build-plugin/blob/master/CONTRIBUTING.md) doc
- [X] Unit tests pass locally with my changes
- [X] No spotbugs warnings were introduced with my changes
- [X] I have interactively tested my changes

### CODE REVIEW

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
Thanks for the pull request!  Nicely done.

Could you also update the bom-2.332.x line to be bom-2.346.x so that the automatically maintained dependencies are synchronized with the minimum Jenkins version?

Refer to https://www.jenkins.io/doc/developer/tutorial-improve/update-base-jenkins-version/ for more details

**Comment by anurag-sachan** [comment]
@MarkEWaite Done. ✅

**Comment by anurag-sachan** [comment]
Sorry, I am newbie to this.
Is it fine or do I need to do something else?

**Review by MarkEWaite — APPROVED** [review]
Thanks!  Fix complete!

**Comment by MarkEWaite** [comment]
> @MarkEWaite Sorry, I am newbie to this. Is it fine or do I need to do something else?

Thanks for checking and thanks for submitting the improvement!

**Pull request merged**
